// Copy the framework-free game modules into supabase/functions/_shared so the Edge Function
// bundles exactly the code the browser runs. `node scripts/sync-shared.mjs --check` fails if stale.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILES = ['tactics/src/data.js', 'tactics/src/grid.js', 'tactics/src/battle.js',
  'arena/src/economy.js', 'arena/src/stronghold.js', 'arena/src/server-core.js'];
const check = process.argv.includes('--check');
let stale = [];
for (const f of FILES) {
  const src = readFileSync(join(root, 'public', f), 'utf8');
  const dst = join(root, 'supabase/functions/_shared', f);
  const banner = `// GENERATED by scripts/sync-shared.mjs from public/${f}. Do not edit.\n`;
  const want = banner + src;
  if (check) { if (!existsSync(dst) || readFileSync(dst, 'utf8') !== want) stale.push(f); continue; }
  mkdirSync(dirname(dst), { recursive: true });
  writeFileSync(dst, want);
}
if (check && stale.length) { console.error('Out of sync (run node scripts/sync-shared.mjs):', stale.join(', ')); process.exit(1); }
console.log(check ? 'shared modules in sync' : `synced ${FILES.length} modules`);
