// GENERATED by scripts/sync-shared.mjs from public/tactics/src/data.js. Do not edit.
// Wildwood Tactics: all rules data lives here (classes, abilities, tiles, items, guilds).

export const W = 12, H = 12;

export const T = { GROUND: 0, GRASS: 1, OVERGROWN: 2, BUSH: 3, BOULDER: 4, PILLAR: 5, TREE: 6, BARE: 7, CORRUPT: 8 };

export const TILE = {
  [T.GROUND]:    { name: 'Clearing', cost: 1 },
  [T.GRASS]:     { name: 'Grass tufts', cost: 1, desc: 'A Wizard can entangle it into difficult terrain.' },
  [T.OVERGROWN]: { name: 'Overgrown', cost: 2, desc: 'Difficult terrain: costs 2 movement.' },
  [T.BUSH]:      { name: 'Bush', cost: 1, desc: 'A Rogue ending a turn here becomes Hidden.' },
  [T.BOULDER]:   { name: 'Boulder', block: true, desc: 'Impassable. Half cover against ranged attacks.' },
  [T.PILLAR]:    { name: 'Rock pillar', block: true, los: true, desc: 'Full cover: blocks line of sight.' },
  [T.TREE]:      { name: 'Leafy tree', block: true, los: true, flammable: true, desc: 'Blocks sight. Flammable. Rangers beside it aim better.' },
  [T.BARE]:      { name: 'Bare trunk', block: true, fell: true, desc: 'Half cover. A Barbarian can fell it.' },
  [T.CORRUPT]:   { name: 'Corrupted tree', block: true, fell: true, desc: 'Lashes anyone ending a turn next to it for 3 damage.' },
};

export const FIRE_DMG = 3, LASH_DMG = 3, FIRE_ROUNDS = 3;

// kind: attack (targets a unit) | cleave (self, hits all neighbours) | aoe (3x3 at a tile) | heal | stance (free)
export const ABIL = {
  strike:   { name: 'Strike', kind: 'attack', range: 1, dmg: 4, acc: 95, anim: 'melee', desc: 'Sword strike.' },
  bash:     { name: 'Shield Bash', kind: 'attack', range: 1, dmg: 2, acc: 95, cd: 2, push: true, anim: 'melee',
              desc: 'Push the target 1 tile. If it slams into rock, a tree or another unit: +2 damage and Stunned.' },
  chop:     { name: 'Chop', kind: 'attack', range: 1, dmg: 5, acc: 90, fell: true, anim: 'melee', desc: 'Heavy axe blow. Can fell bare trunks.' },
  cleave:   { name: 'Cleave', kind: 'cleave', dmg: 4, cd: 2, anim: 'melee', desc: 'Sweep all 8 surrounding tiles. Fells bare and corrupted trees.' },
  shoot:    { name: 'Longshot', kind: 'attack', range: 7, dmg: 2, distScale: 0.5, acc: 80, ranged: true, proj: 'arrow',
              desc: 'Damage grows with distance (+1 per 2 tiles). +20% hit next to a leafy tree.' },
  aimed:    { name: 'Aimed Shot', kind: 'attack', range: 8, dmg: 2, distScale: 0.5, mult: 1.5, acc: 90, ignoreCover: true, ranged: true, cd: 3, proj: 'arrow',
              desc: 'x1.5 damage and ignores half cover.' },
  stab:     { name: 'Twin Daggers', kind: 'attack', range: 1, dmg: 5, acc: 95, anim: 'melee', desc: 'Strike from Hidden for a guaranteed x2 crit.' },
  crossbow: { name: 'Crossbow', kind: 'attack', range: 5, dmg: 3, acc: 80, ranged: true, proj: 'bolt', desc: 'Ranged shot. Crits from Hidden too.' },
  bolt:     { name: 'Arcane Bolt', kind: 'attack', range: 5, dmg: 3, acc: 90, ranged: true, spell: true, proj: 'orb', desc: 'Reliable magic missile.' },
  fireball: { name: 'Fireball', kind: 'aoe', range: 5, dmg: 3, cd: 3, spell: true, ignite: true, proj: 'fire',
              desc: '3x3 blast (hurts allies too). Sets leafy trees ablaze, leaving fire for 3 rounds.' },
  entangle: { name: 'Entangle', kind: 'aoe', range: 5, dmg: 0, cd: 2, overgrow: true, proj: 'vine',
              desc: 'Grass and clearings in a 3x3 area become overgrown difficult terrain.' },
  heal:     { name: 'Healing Potion', kind: 'heal', range: 3, amount: 6, cd: 2, proj: 'potion', desc: 'Throw a potion to an ally (or self): +6 HP.' },
  axe:      { name: 'Axe Strike', kind: 'attack', range: 1, dmg: 4, acc: 95, stanceBonus: true, anim: 'melee', desc: '+2 damage in Offense stance.' },
  flask:    { name: 'Potion Flask', kind: 'heal', range: 3, amount: 8, consumable: 'potion', proj: 'potion', desc: 'Consumable brewed at home: +8 HP to an ally in range. Uses your action.' },
  stance:   { name: 'Swap Stance', kind: 'stance', free: true,
              desc: 'Free, once per turn. Offense: axe, +2 damage. Defense: raise the round shield, -2 damage taken.' },
};

export const CLASSES = {
  knight:    { name: 'Knight', role: 'Tank', model: 'Knight', hp: 24, move: 3, armor: 1, prefer: 1,
               gear: { R: 'sword_1handed', L: 'shield_badge' }, abilities: ['strike', 'bash'],
               passive: 'Hold the Line: enemies that step next to the Knight must stop. Armor 1.' },
  barbarian: { name: 'Barbarian', role: 'Melee AoE', model: 'Barbarian', hp: 22, move: 4, prefer: 1,
               gear: { R: 'axe_2handed' }, abilities: ['chop', 'cleave'],
               passive: 'Clears bare trunks to open new paths.' },
  ranger:    { name: 'Ranger', role: 'Sniper', model: 'Rogue', hp: 15, move: 4, prefer: 5,
               gear: { R: 'bow_withString' }, abilities: ['shoot', 'aimed'],
               passive: 'Eagle Eye: +20% hit chance next to a leafy tree.' },
  rogue:     { name: 'Rogue', role: 'Stealth', model: 'Rogue_Hooded', hp: 16, move: 5, prefer: 1,
               gear: { R: 'dagger', L: 'dagger' }, abilities: ['stab', 'crossbow'],
               passive: 'Hidden on bushes: can only be targeted from 1 tile, next attack is a guaranteed crit.' },
  wizard:    { name: 'Wizard', role: 'Support', model: 'Mage', hp: 14, move: 3, prefer: 4,
               gear: { R: 'staff', L: 'spellbook_open' }, abilities: ['bolt', 'fireball', 'entangle', 'heal'],
               passive: 'Controls the field with fire, vines and potions.' },
  fighter:   { name: 'Fighter', role: 'Versatile', model: 'Ranger', hp: 20, move: 4, prefer: 1,
               gear: { R: 'axe_1handed' }, abilities: ['axe', 'stance'],
               passive: 'Swaps freely between offense and a defensive shield stance.' },
};
export const CLASS_KEYS = Object.keys(CLASSES);

// slot: R / L hand model override, 'shield' = Fighter's defense-stance shield. Items without slot are trinkets.
export const ITEMS = {
  masterblade:  { name: 'Masterwork Blade', cls: 'knight', slot: 'R', model: 'sword_2handed_color', mods: { dmg: 2 }, desc: '+2 damage' },
  spiked:       { name: 'Spiked Kite Shield', cls: 'knight', slot: 'L', model: 'shield_spikes_color', mods: { hp: 4, bash: 2 }, desc: '+4 HP, Shield Bash +2 damage' },
  clansword:    { name: 'Clan Greatsword', cls: 'barbarian', slot: 'R', model: 'sword_2handed', mods: { dmg: 2 }, desc: '+2 damage' },
  pelt:         { name: 'Bear Pelt', cls: 'barbarian', mods: { hp: 6 }, desc: '+6 HP' },
  ironbow:      { name: 'Ironwood Longbow', cls: 'ranger', slot: 'R', model: 'bow', mods: { dmg: 1, range: 1 }, desc: '+1 damage, +1 range' },
  hawkquiver:   { name: 'Hawk-feather Quiver', cls: 'ranger', mods: { acc: 10 }, desc: '+10% hit chance' },
  repeater:     { name: 'Repeating Crossbow', cls: 'rogue', slot: 'L', model: 'crossbow_1handed', mods: { dmg: 1, range: 1 }, desc: '+1 damage, +1 crossbow range' },
  smoke:        { name: 'Smoke Bombs', cls: 'rogue', mods: { move: 1 }, desc: '+1 move' },
  elderwand:    { name: 'Elder Wand', cls: 'wizard', slot: 'R', model: 'wand', mods: { spell: 2 }, desc: '+2 spell damage' },
  grimoire:     { name: 'Verdant Grimoire', cls: 'wizard', slot: 'L', model: 'spellbook_closed', mods: { heal: 3 }, desc: '+3 healing' },
  guildshield:  { name: 'Guild Round Shield', cls: 'fighter', slot: 'shield', model: 'shield_round_color', mods: { armor: 1, hp: 3 }, desc: '+1 armor, +3 HP' },
  whetstone:    { name: 'Whetstone', cls: 'fighter', mods: { dmg: 1 }, desc: '+1 damage' },
  boots:        { name: 'Trail Boots', cls: 'any', mods: { move: 1 }, desc: '+1 move' },
  chainshirt:   { name: 'Chain Shirt', cls: 'any', mods: { hp: 4 }, desc: '+4 HP' },
};

export const GUILDS = [
  { name: 'Ashen Fangs', tint: 0xff9c7a },
  { name: 'Crimson Oath', tint: 0xff7f8f },
  { name: 'Grey Ravens', tint: 0xb9c2d6 },
  { name: 'Thornwake Company', tint: 0xc6ff8a },
  { name: 'Iron Lanterns', tint: 0xffd47a },
  { name: 'Duskmire Pact', tint: 0xc59bff },
];
export const BOSS_GUILD = { name: 'The Hollow Crown', tint: 0xb48cff };

/** Sum of item modifiers for a gear list. */
export function gearMods(gear) {
  const m = {};
  for (const id of gear) for (const [k, v] of Object.entries(ITEMS[id].mods)) m[k] = (m[k] || 0) + v;
  return m;
}

/** Hand models for a hero/unit, taking items and Fighter stance into account. */
export function gearModels(h) {
  const g = { ...CLASSES[h.cls].gear };
  let shield = 'shield_round';
  for (const id of h.gear) {
    const it = ITEMS[id];
    if (it.slot === 'shield') shield = it.model; else if (it.slot) g[it.slot] = it.model;
  }
  if (h.cls === 'fighter') g.L = h.stance === 'defense' ? shield : undefined;
  return g;
}

export function maxHpOf(h) { return CLASSES[h.cls].hp + (gearMods(h.gear).hp || 0); }

/** Add an item to a hero, replacing whatever occupied the same slot. */
export function equip(h, id) {
  const slot = ITEMS[id].slot;
  if (slot) h.gear = h.gear.filter(g => ITEMS[g].slot !== slot);
  const before = maxHpOf(h);
  h.gear.push(id);
  h.hp += Math.max(0, maxHpOf(h) - before);
}
